from . import student
from . import teacher
from . import fees_structure
from . import parents
from . import admission
from . import sale
from . import invoice
from . import student_complaint
from . import product
from . import product_brand
from . import purchase
from . import res_users